language: node_js
sudo: false
node_js:
  - node
branches:
  only:
    - master
cache:
  directores:
    - node_modules
before_install:
  - yarn upgrade
install:
  - yarn
script:
  - yarn test
  - yarn run coveralls
